### ISSUE TITLE
Allow manual entry of desired joint angles on manual screen

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#113]
Allow user to enter explicit values for each joint on the manual screen.  This is helpful when envisioning a particular configuration (such as in Mission Control, etc.).

**Comment by streadgold** [comment]
Saving these references here so I don't forgot what I was planning to do:

https://kivy.org/doc/stable/api-kivy.uix.bubble.html
https://kivy.org/doc/stable/api-kivy.uix.gridlayout.html

Adding buttons to a grid layout inside a bubble should be a good way to make a "popup" numpad type thing

**Comment by streadgold** [comment]
Done
