### ISSUE TITLE
Switch to Raspberry Pi 4

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#117]
Currently the installation steps do not work on the Pi 4. Don't know why. Seems to work fine at first but then after a reboot the xserver completely fails and Pi is terminal only.

**Comment by streadgold** [comment]
Solved. The "sudo apt-get install git-all" command does.... something. No idea what. but it completely nukes the graphics ability of the pi. Also - it's not needed. Git comes installed by default. Removed that instruction from the setup instructions
