### ISSUE TITLE
Potential SARJ drift

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#118]
When running in live mode for several hours it looks like the SARJs begin to drift by quite a bit. Both stay in sync with each other but they both appeared to be roughly 45 degrees off the actual angle after running for approximately 4 hours.

**Comment by SWGlassPit** [comment]
Does the drift happen if the joints are commanded through multiple full
rotations via the calibration screen? Might rule out something simple like
having the wrong number of encoder pulses per rotation

**Comment by ISS-Mimic** [comment]
Yes drift still occurs through manual control, a single full rotation appears to be about 30 degrees off

**Comment by ISS-Mimic** [comment]
@juggler2000 do we think this is solved now?

**Comment by juggler2000** [comment]
Yes, solved.
