### ISSUE TITLE
Build Instruction - Install motors in components 

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#121]
Add to "Install motors in components" section on Build Instruction Wiki

    mount motor in truss print (screw and don't jam magnet)
    include wiring notes/sequences (especially for use inclusion of PCBs)

***or provide me word document and I can organize/get it into the wiki***

**Comment by juggler2000** [comment]
This will be part of the EDU activities run by the teachers, so closing here.
