### ISSUE TITLE
Build Instruction - 3D Print Components

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#123]
Add to "3D Print Components" section of "Build Instruction" wiki:

    list all components that need to be printed (and explain where on GitHub stl files are)
    any print specifics like black and white for Soyuz and Progress or specify other colors
    finishing instruction for magnet insertion

***or provide me word document and I can organize/get it into the wiki***

**Comment by Digisembler** [comment]
This is being worked by @SpaceTowel as part of #221
