### ISSUE TITLE
Major power draw problem

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#124]
Some kind of issue where we seem to be drawing too much current from the Raspberry Pi USB ports, likely due to the added neopixels and servo motors being powered directly off the USB port. 

Seems like the solution is to separately power the servos and/or the neopixels so they don't all draw from the Raspi USB ports which should not be used to provide more than 1.2A total from all 4 ports.

**Comment by juggler2000** [comment]
Hmmm... disconnecting one of the servos solves the problem.  Sometimes, so does disconnecting half of the LEDs.  Initial test of powering STBD servo separately (from hacked USB cable plugged into same battery power brick that's powering the Pi). Yielded good results, but only from nominal motor commanding, so nothing drawing much current.

**Comment by streadgold** [comment]
Solved with the powered USB hub
