### ISSUE TITLE
Random Port SARJ misbehavior

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#131]
Works fine, then sometimes runs away perpetually spinning.

Worked fine for 2 hrs, then seemingly spontaneously manifested the problem.  Prior grounding issue did not appear to be cause.

Having made no changes but starting again, it works fine. Note that live data feed is currently down but was working during bug manifestation. Seems likely unrelated.

Doesn't seem like it should be a power issue since Hall encoder sensors are powered from pi which was still up, battery pack over 50 perc.

**Comment by ISS-Mimic** [comment]
Closing old issues that are likely due to connection problems - which should be solved by our hdmi-ification
