### ISSUE TITLE
Add smartflip flag toggle on Pi

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#133]
Want to be able to turn on/off the smartflip flag from the Pi. One flag for BGAs, one for SARJs.

**Comment by juggler2000** [comment]
Note that these flags are already in place on the Arduino.  The request is to add a feature to the Pi to allow a user to toggle the flag.

**Comment by streadgold** [comment]
Done, in dev branch. will send "smartflip=1 " to activate and "smartflip=0 " to deactivate
