### ISSUE TITLE
Serial issue on new SGANT test

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#140]
Testing the stepper motors on the new SGANT extra build and when we plug in the arduino the pi completely locks up but after removing the print statements from the arduino side the pi doesn't lock up but it becomes super laggy. Removing the USB cable instantly solves the problem.

Feel like we've had this problem before

**Comment by streadgold** [comment]
Switched to Servos and finished the new code. And the problem still persists.

**Comment by ISS-Mimic** [comment]
SOLVED! Problem was the GUI was using "timeout=0" in the serial write command, but timeout is for serial read timeout, we must use "write_timeout=0" to make a non-blocking serial write command
