### ISSUE TITLE
Vinyl Cutting for Solar Cell Profile

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#144]
Susan is to create an SVG file with a solar cell grid for Chen to create on a vinyl cutter

**Comment by SpaceTowel** [comment]
![Solar Cell Profile Vinyl cutting at work](https://user-images.githubusercontent.com/58833710/73125236-323a8280-3f6a-11ea-9b90-e827fbe8326c.jpg)
