### ISSUE TITLE
Consider increase serial data rate between pi and arduino

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#154]

**Comment by juggler2000** [comment]
This would be of primary benefit during accelerated playback.  Currently, the motion is in discrete bursts, corresponding to position changes across the 1 second transmission gaps.  Another way to address this is to add a velocity-matching loop that couples with the position loop to estimate rate while holding close to position.  Likely simpler just to up the serial update rate and keep the existing control loop.
