### ISSUE TITLE
Defeat COVID-19

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#156]
Objective: Survive

**Comment by SWGlassPit** [comment]
Hey!

Why am I responsible for this? 🤣

**Comment by ISS-Mimic** [comment]
Cause it's a bug that impacts Mimic and you solve our bugs!

**Comment by SWGlassPit** [comment]
Try

`set covid19_is_spreading = false`

**Comment by ISS-Mimic** [comment]
hmm "User does not have sufficient administrative permission for this action"

**Comment by SWGlassPit** [comment]
Crap

**Comment by Digisembler** [comment]
Someone fed the bug water after dark... now it's everywhere...
