### ISSUE TITLE
Upload Blender Model Exporting Instructions

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#157]
Chen, I remember you taking a great set of notes and tips for the blender model split up process. Could you post those somewhere here (wiki) so if we need to re-export some of the models we can follow your amazing instructions?

**Comment by SpaceTowel** [comment]
Done!  uploaded instruction file to wiki.  
https://github.com/ISS-Mimic/Mimic/blob/master/Wiki/How%20to%20split%20from%20blender%20model_2019.12.30.pdf
