### ISSUE TITLE
IEA connector idea for interfacing with slip ring leads

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#163]
Would like something that allows leads from slip ring to be able to be inserted/removed from truss w/o cutting.  Most connectors are too big. 

Screw terminals?  Smaller than 0.1” spacing? 
Ribbon cable?  Might not be sufficient to carry current.  Could potentially use multiple traces for single current path (i.e. 4 traces for 2 motor power lines).

**Comment by ISS-Mimic** [comment]
Screw terminals should work
