### ISSUE TITLE
Printed Microcontroller Holder

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#170]
Would be nice to have a method of securing the Metro board to the frame.

CAD model of the metro should be here:

https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/2488%20Adafruit%20Metro%20328

**Comment by cactus314** [comment]
Preference for a holder that can be fastened to the 2040 extrusion or just held in place with a light press-fit?
![image](https://user-images.githubusercontent.com/10385574/123806900-ffaa5d00-d8b4-11eb-95f8-eb351296422c.png)

**Comment by Digisembler** [comment]
Patrick's solution seems to work well, might watch out for future issue of the screw hole pillars breaking off

**Comment by cactus314** [comment]
Uploaded the Metro 2040 Mount to the structural components directory of the 3D Printing folder.  I'll let @streadgold rename/move it if he wants.  It fits the middle Metro pushed all the way against the t-brackets without too much side torque from the HDMI connection.  I'll design a separate mount for the Metro Mini I intend to use for the NeoPixels.
![image](https://user-images.githubusercontent.com/10385574/126905371-3056dc03-c413-4d9e-b88c-17275a83a426.png)

**Comment by cactus314** [comment]
Uploaded STLs for mounts for the Metro Mini (i.e, Arduino Nano) considered for use to control Neopixels,  as well as a mount for the Sabrent 4-Port USB Hub.  These additions might close out this issue.  I'll let someone else (@streadgold / @ISS-Mimic ) decide.
![image](https://user-images.githubusercontent.com/10385574/127377528-8ae26755-2d92-402e-bef1-c0ed17025ea0.png)
![image](https://user-images.githubusercontent.com/10385574/127377589-33bfb100-4d24-4da1-9d6a-6a6db1aae44f.png)

**Comment by streadgold** [comment]
Nice! Looks good to me
