### ISSUE TITLE
Improve Serial Port Detection

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#192]
Currently, the serial ports are hard coded to ACM0 ACM1 ACM2 and ACM3. These are the most comment ports for our devices, but other devices or more/less devices would not work.

Added code to the "serial_ports" which checks all possible ports - this worked great but when actually using it when the connected devices there was considerable lag. We call it every 1 second ish and try to write to all those ports so... yeah.

Would be nice to detect whenever a device is plugged in or removed and update arduino_count accordingly (also need to handle other serial ports)

**Comment by dallasbrittany** [comment]
Are you okay with having to pip3 install pyudev? I can add it to the instructions list.

I changed things so you can either fill out config.json and then run with python3 GUI.py --config, or you can just run the normal way, and it'll find things with ID_VENDOR that includes Arduino, Adafruit, or FTDI. Metro M0 boards seem to use Adafruit, but I wanted to be able to support other Arduino boards too. I tested with the Uno (Arduino), Mega (Arduino), and Nano (FTDI).

I haven't made it so it detects when you plug something in. I figured it was good enough to just make sure you plug things in before you start the GUI. But I can make it detect if you think it's useful. What do you think? I'm not sure what your use case is like.

**Comment by streadgold** [comment]
Sure! Asynchronous device monitoring sounds great

**Comment by dallasbrittany** [comment]
Yeah, it would really help if I could type correctly the first time.

This:
`NameError: name 'OPEN_SERIAL_PORT' is not defined`
happened because it's supposed to be plural. Sorry. Fixed now.
