### ISSUE TITLE
Update BOM with price of PCBs

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#225]
@cactus314 if you could provide the total price of the PCB service I'll update that in our BOM

**Comment by cactus314** [comment]
@streadgold : $107.17 (merchandise) + $13.07 (shipping) = $120.24 total
Though if I add up all the line items myself, I come up with only $106.32 in merchandise.  I'm not quibbling though.
![image](https://user-images.githubusercontent.com/10385574/126631154-384abb59-1cb4-426f-a891-ffb9d43f4a12.png)

**Comment by ISS-Mimic** [comment]
Welp it is cheaper to get the assembled PCBs than to DIY them. Would not have guessed that.
