### ISSUE TITLE
Add Micro gear dc motor screws to BOM

### ISSUE THREAD

**Issue by Digisembler** [ISS-Mimic/Mimic#226]
Went to go fix the S3 motor mount issue #204 and didn't have the nominal screw length, and it needs to be added to the BOM regardless

**Comment by juggler2000** [comment]
M1.6x 0.35, 5mm length, hex head. Will look for a vendor.

**Comment by juggler2000** [comment]
This seems like a good option. Countersunk, with torx head. https://www.mcmaster.com/92703A142

**Comment by cactus314** [comment]
> This seems like a good option. Countersunk, with torx head. https://www.mcmaster.com/92703A142

Do the outboard truss pieces also need to be modified to accommodate that countersink?
Should I order some and try them on my build before adding them to the BOM?

**Comment by juggler2000** [comment]
Utilized same screws as ordered for PIRB unit.  Updated BOM to add item and reflect updated costs.
