### ISSUE TITLE
Develop IROSA CAD/Print

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#230]
IROSA print/model is in progress - trying to track everything we are working on in issues

**Comment by Digisembler** [comment]
Doh, I meant to print it yesterday before I left.  i'll try again at home for a full array print (which fits on my ender 3 at 45 degrees). Last attempt seemed workable, might still add an anti-rotation feature.

**Comment by SpaceTowel** [comment]
redesign zip tie hole
