### ISSUE TITLE
Changes to Frame BOM

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#231]
The Frame BOM calls for 3 packages of 2020 rubber feet (4 per package, 9 total required).  However, only 8 rubber feet are required.  The central rear support doesn't use a rubber foot because the 50mm rod support is flush with the end of the 2020 extrusion and there's no room for the foot to slip on.
![image](https://user-images.githubusercontent.com/10385574/126882468-c90fa655-8db1-4125-a51a-2f7307ba777a.png)

Instead, the BOM should call for 2 packages of 2020 rubber feet (8 total required) and one package of [2020 endcaps](https://www.zyltech.com/2020-end-cap-cover-10-pack/).  This is a package of ten and might be overkill to spend $4.45 for a single needed part, so we could offer a 3D-printed alternative.  The printed endcap on the left is from Thingiverse ([Thing 813368](https://www.thingiverse.com/thing:813368)) and fits quite snug.  The purchased part is on the right.  The printed part in the center, also from Thingiverse, doesn't fit very tight.
![image](https://user-images.githubusercontent.com/10385574/126882493-519ff19c-4665-4a9d-8cc2-a65a78c56112.png)

**Comment by juggler2000** [comment]
Printed version looks sufficient to me.  We can have that as the primary plan, with purchased 10-pack of caps as the backup.
