### ISSUE TITLE
Potential double listing of motor connectors in the BOM

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#235]
It looks to me like the [motor connectors](https://www.amazon.com/1-5MM-Female-Double-Connector-Cable/dp/B07HSZJ2PM/) (which are ordered along with associated wiring) are listed both under [Essential Parts](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials#essential-parts) and also listed in the [DIY PCB](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials#custom-printed-circuit-boards-pcbs---do-it-yourself-diy) section.  These are only required if you're building your own boards from scratch (i.e., not ordering pre-fab boards) and should be removed from the "Essential Parts" list, correct?
![image](https://user-images.githubusercontent.com/10385574/126912513-655ac3d3-4643-45be-9e9e-d8389c682796.png)

**Comment by streadgold** [comment]
yep. look who just saved us $7.99
