### ISSUE TITLE
Changes/Additions to the Raspberry Pi / Mimic Control Unit BOM

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#236]
Need to add/change the following to the [RPi BOM](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials#raspberry-pi--mimic-control-unit):

1. Consider changing the recommended CanaKit power supply to [this one](https://smile.amazon.com/gp/product/B097P2NLVH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) (Amazon) from iUniker.  It has the same voltage/current specs and price but includes a power switch.
2. Add [Sabrent 4-Port USB Hub](https://smile.amazon.com/gp/product/B00TPMEOYM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) (Amazon)
3. Add 4 [USB-A to USB-Micro (3-ft) cables](https://smile.amazon.com/gp/product/B011KLFERG/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) (Amazon), or suggest digging some out of the surplus cable box most people seem to have sitting around.  Must be data cables - not just charging cables.  These connect from the USB hub to the Metro 0's (motors) and to the Metro Mini (Neopixels).

**Comment by juggler2000** [comment]
I agree with these suggestions.  @cactus314, feel free to make the updates and clos this issue when ready.  Thanks.
