### ISSUE TITLE
Change main screen animation from clock event to actual animation? (or unschedule)

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#24]
Might be better to have the orbiting ISS icon on the main screen be an animation object rather than a moving clock event thing (not sure if animation if better). 

If it remains a clock event, it might be good to unschedule the event when not on the main screen (currently the animation keeps going even when the user is on a different screen). This might reduce lag. 

Or just move animations to a background thread if I ever figure out how to do that.

**Comment by ISS-Mimic** [comment]
Using cProfile we are fairly confident this isn't a major cause of lag
