### ISSUE TITLE
Inconsistent drill hole sizes in Mimic Shield

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#240]
In the latest batch of Mimic Shields I received (July 2021), the thru-holes for P1 (pins 8 - GND) are larger in diameter than the other holes.  They'll still work, just a sloppier fit.  Was this intentional?
We should also mention in the documentation that J6 (I2C connection) is not meant to have anything soldered to it (or at least I assume not), and also that this isn't a full shield - i.e., not all of the sockets in the motor shield below will have a pin inserted.
![image](https://user-images.githubusercontent.com/10385574/127709411-76c1e56d-22c5-4469-b178-bc381e903d6f.png)

**Comment by ISS-Mimic** [comment]
oh weird yeah maybe replaced the component and I didn't realize it had different hole sizes. I'll fix that, glad it still works. good note about J6, it's just a test port that I don't think we've even used haha
