### ISSUE TITLE
Need a new 2020 frame mount for the latest HDMI Breakout PCB

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#243]

**Comment by cactus314** [comment]
Have a version I'm testing, but it needs improvement.
![image](https://user-images.githubusercontent.com/10385574/128100092-d4e1a52e-9dbd-4379-990c-e134a09f7521.png)

**Comment by SpaceTowel** [comment]
felt foot.

**Comment by cactus314** [comment]
Updated mount STL uploaded.  May change the design later.
