### ISSUE TITLE
Specify/recommend white as the color of the custom IEA PCB boards

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#247]
Under [Pre-Assembled PCB Ordering Instructions](https://github.com/ISS-Mimic/Mimic/wiki/How-to-Order-PCBs#pre-assembled-pcb-ordering-instructions), I think we should explicitly recommend the color white for the IEA boards so that they blend in better with the 3D-printed truss segments.

![image](https://user-images.githubusercontent.com/10385574/128178995-d95ded80-04ab-4c51-9605-42ec02dcf3d3.png)

**Comment by SpaceTowel** [comment]
fixed
