### ISSUE TITLE
Error in manual instructions for intallation of Kivy on Raspberry Pi

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#248]
In Step 10 of the manual software setup instructions, ("[Install Kivy](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Mimic-Software-Setup-Instructions#10-install-kivy)"), 'install' is left out of the provided commands.  It's correct in setup.py, it just needs to be reflected in the manual setup portion of the Wiki.

![image](https://user-images.githubusercontent.com/10385574/128252882-a4797304-3bb6-4d8b-b9e3-60f50296213d.png)

**Comment by SpaceTowel** [comment]
fixed!
