### ISSUE TITLE
New part order with new silk screen update from ticket 241 + 242

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#250]

**Comment by cactus314** [comment]
@juggler2000 - Just to be clear.  You want me to use HDMI breakout boards and IEA Boards with the updated silkscreens on the build I'm currently working on?  That'll slow me down a little, but that's okay.  We have time.
@streadgold - What's the timeframe for updating the gerber files for those two boards?  Let me know when they're ready to go and I'll get the new boards on order.  I might have to go through the process of verifying the orientation of the screw terminals with JLCPCB again.

**Comment by streadgold** [comment]
Should be able to do that tomorrow if I remember

**Comment by cactus314** [comment]
> Should be able to do that tomorrow if I remember

Do you need dimensions for the offsets/terminal blocks?

**Comment by streadgold** [comment]
Nope I already have the dimensions

**Comment by juggler2000** [comment]
Yes, I was thinking of using the revised boards in your design, for photos and later debugging purposes. If that's a significant slowdown for you, then just proceed with what you have. Sounds like Sam is on it, though.

**Comment by cactus314** [comment]
@streadgold & @juggler2000 - On the HDMI breakouts, there's an inventory shortage of the header pins @ JLCPCB (presumably the ones for the servos).  I'm tempted to order anyway and solder in those pins myself just to keep things moving.  Thoughts?
![image](https://user-images.githubusercontent.com/10385574/128694611-c4196db2-55d3-488f-bfd3-4b78b25ef8b6.png)

**Comment by cactus314** [comment]
Or is that not how it works and they'll hold production until the parts become available?

**Comment by cactus314** [comment]
Now that I'm exploring the tool, I see you can change parts.  Is this an acceptable replacement?
![image](https://user-images.githubusercontent.com/10385574/128696132-23ac054c-89d1-4db5-aa47-80c40523498e.png)
![image](https://user-images.githubusercontent.com/10385574/128696163-259d1df6-a8e4-4983-b9c8-7abb956110bc.png)

**Comment by cactus314** [comment]
Or basically any straight three-pin header?
![image](https://user-images.githubusercontent.com/10385574/128696400-66f4bfe3-7649-401a-96aa-6ab0b9a9cdae.png)

**Comment by streadgold** [comment]
Yes any 2.54mm pitch 3 pin header should work, that looks fine to me. 

To answer your first question I'm not sure if they would hold product. I think if you just uncheck the part it would probably go through and just ignore that part

**Comment by cactus314** [comment]
Had a minimum order of 50pcs for the 3-pin headers... not sure why, but fortunately they're super cheap.
