### ISSUE TITLE
Limit lateral motion of ISS pressurized modules relative to ITS

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#255]
Need a way to mechanically/magnetically connect S0 to Destinty Lab via the S0/Destiny connector to prevent side-to-side shifting of the module stack - especially during "disco mode" - to prevent interference between the HRSRs and the port/starboard elements connected to Node 1.

**Comment by ISS-Mimic** [comment]
Done with the new S0/Lab designs
