### ISSUE TITLE
Update Start up guide

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#258]
1) Update step 1, no longer need batteries
2) Step 2, is the connector listed correct?  do we need to update photo?

**Comment by ISS-Mimic** [comment]
Correct, no more batteries. And step 2 is not correct either, just need to plug in the USB hub

**Comment by cactus314** [comment]
[Step 3](https://github.com/ISS-Mimic/Mimic/wiki/Mimic-Startup-Shutdown-Procedure#3-start-the-mimic-graphical-user-interface-gui) will change as well.  So long as there is an internet connection, the RPi clock should set itself, and I think I have the desktop icon working to launch the Mimic code without requiring going through a terminal window - though we should include instructions for both methods just in case.

**Comment by streadgold** [comment]
@cactus314 so I'm not sure if there's something about the boeing external network preventing this, but when testing at work I have always had to set the time manually. I'd say leave that in there to double check just in case
