### ISSUE TITLE
Import to fusion and convert to mm and re-upload

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#260]
- [ ] LoFi_ITS-S0.stl
- [ ] LoFi_ITS-S0-Destiny_Connector.stl
- [ ] LoFi_ITS-1.stl
- [ ] LoFi_ITS-P1andS1.stl
- [ ] LoFi_ITS-1_AmmoniaTank.stl
- [ ] LoFi_ITS-1_Mounts.stl
- [ ] LoFi_ITS-1_TRRJ-Beam.stl
- [ ] LoFi_ITS-4_5-simple.stl
- [ ] LoFi_ITS-4_5-complex.stl
- [ ] LoFi_ITS-6-simple.stl
- [ ] LoFi_ITS-6_IEA-complex.stl
- [ ] LoFi_ITS-6_LS-complex.stl
- [ ] LoFi_Zarya.stl
- [ ] LoFi_DockingCompartment.stl
- [ ] LoFi_MRM1.stl
- [ ] LoFi_Zvezda.stl
- [ ] LoFi_Zvezda_End.stl
- [ ] LoFi_OutboardRadiatorBase.stl
- [ ] LoFi_Canadaarm2_Arm.stl
- [ ] LoFi_Canadaarm2_EE.stl
- [ ] LoFi_MobileBaseSystem_Base.stl
- [ ] LoFi_MobileBaseSystem_Body.stl
- [ ] LoFi_DestinyLab-1.stl
- [ ] LoFi_DestinyLab-2.stl
- [ ] LoFi_HarmonyNode2-1.stl
- [ ] LoFi_HarmonyNode2-2.stl
- [ ] LoFi_UnityNode1-1.stl
- [ ] LoFi_UnityNode1-2.stl
- [ ] LoFi_Leonardo_End.stl
- [ ] LoFi_LEO-COF-barrel.stl
- [ ] LoFi_COF-End.stl
- [ ] LoFi_BEAM.stl
- [ ] LoFi_PMA123.stl
- [ ] LoFi_IDA23.stl
- [ ] LoFi_ITS-3-simple.stl
- [ ] LoFi_ITS-S3-complex.stl
- [ ] LoFi_ITS-P3-complex.stl
- [ ] LoFi_ITS-4_SARJ_Connector.stl
- [ ] LoFi_JEM-PM.stl
- [ ] LoFi_JEM-PS.stl
- [ ] LoFi_Solar_Array_base.stl
- [ ] LoFi_Solar_Array_end.stl
- [ ] LoFi_ITS-3_SARJ_Gear_Ring.stl
- [ ] LoFi_Outboard-Truss-support.stl
- [ ] LoFi_2020-endcap-tall.stl

**Comment by ISS-Mimic** [comment]
not in fusion, but all in mm I believe now? someone else can maintain the fusion lofi model
