### ISSUE TITLE
Anti rotation feature for front of station

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#261]
Would be nice to have some feature between Node 2 and fwd Lab that prevents the imbalanced JEM + COF from rotating

Also applies to Node 3

**Comment by cactus314** [comment]
Since Node 2 is essentially pinned by one of the vertical upright stainless rods, doesn't that pretty well lock its rotation?  Node 3 is free to rotate, but there's not as much mass hanging off the sides of it to cause a problem (so it seems to me).

**Comment by ISS-Mimic** [comment]
You would think so, but not enough apparently with the massive weight of the JEM + EF

**Comment by ISS-Mimic** [comment]
Confirmed, not needed. New node prints are held in place pretty well
