### ISSUE TITLE
Need to upload STLs for Visiting Vehicles

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#262]
The following VV STLs need to be uploaded to the appropriate Visiting_Vehicles 3D Printing directories:

- [x] Dragon
- [x] Starliner
- [x] Cygnus
- [x] HTV

**Comment by cactus314** [comment]
@Digisembler - Something's wrong with the scaling on Cygnus.  It comes in around 1m across in the x-dimension.  If I scale it down to 1%, it looks about right, but I don't know what the actual dimensions should be.

**Comment by Digisembler** [comment]
1% is correct, as the model is apparently full size.  Checking my 3mf file I used to print, i noticed i had already scaled it there, and forgot that when I exported it (which i redid for the upload).

**Comment by Digisembler** [comment]
Got most of Starliner uploaded (SM is too big, even zipped). Added the attributes for Cygnus and Starliner and HTV.
