### ISSUE TITLE
Motor mount screws may need a different supplier

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#272]
Was looking at the BOM and there is only "see all buying options" for the motor mount screws. Seems like they are not widely available. 8mm option was prime though, but cutting the screws seems like a last resort 

Even if choosing the one buying option available we would need to update the prices

**Comment by cactus314** [comment]
Could go with McMaster as the supplier (we already have them for other items).  
https://www.mcmaster.com/m16x6mm/flat-head-screws/system-of-measurement~metric/thread-size~m1-6/length~6-mm/

**Comment by Digisembler** [comment]
Thanks for the suggestion @cactus314!  BOM updated. issue closed.
