### ISSUE TITLE
Add LEDs to Mini Mimic

### ISSUE THREAD

**Issue by Digisembler** [ISS-Mimic/Mimic#274]

**Comment by GodspeedDiscvry** [comment]
Start with this:
[MIMIC LITE LED Patterns.pptx](https://github.com/ISS-Mimic/Mimic/files/7173734/MIMIC.LITE.LED.Patterns.pptx)

**Comment by juggler2000** [comment]
Low-priority task since Lite is not a focus area, however what we build for Mini Mimic can likely be ported to Lite to some degree.

**Comment by juggler2000** [comment]
Changed name to be "Add LEDs to Mini Mimic".  This is a legacy issue from ISS LITE, which is no longer in development.  @GodspeedDiscvry has done work with the LED patterns .pptx file (above as comment) and physical layouts with Mini.  Changing assignment on this to be just @whodat23 .
