### ISSUE TITLE
Need patterns for array panels on ROS modules

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#276]
Physical dimensions and build instructions are needed for the solar array panels(?) on the FGB, SM, and MLM.  I can measure the ones for the FGB and SM from the STEM model when I get it back but will need the dimensions for the MLM and guidance on materials/methods used.

- [x] FGB Panels (folded)
- [x] SM Panels
- [x] MLM Panels

**Comment by ISS-Mimic** [comment]
These components will eventually be printed and vinyl'd btw

**Comment by cactus314** [comment]
> These components will eventually be printed and vinyl'd btw

Any idea on the timeline/priority for getting the panels into CAD/STLs ?

**Comment by ISS-Mimic** [comment]
Done
