### ISSUE TITLE
Create a "MidFi" version of the Z1 Truss?

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#278]
@streadgold's new Z1 Truss model is great, but it requires 8 individual parts to be printed and glued together.  Maybe there's a middle ground where the LoFi version can have the CMG elements modeled along with the antenna booms and dishes that can be printed as a single print.
![image](https://user-images.githubusercontent.com/10385574/139535337-8295dc76-9883-4315-a271-c9ee79da053e.png)

**Comment by ISS-Mimic** [comment]
![image](https://user-images.githubusercontent.com/23327384/139569727-c1ab5ddf-6983-4ba0-87be-4be6bfd4c553.png)

@cactus314 thoughts?

**Comment by ISS-Mimic** [comment]
also you can just copy an image file into a comment and it auto uploads to github thats nifty

**Comment by cactus314** [comment]
Looks great!  Did you emboss the MBM on the forward side?

**Comment by ISS-Mimic** [comment]
Yep MBM is still there!
