### ISSUE TITLE
Upload STLs in Binary Format

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#279]
It's been noted that some of the posted STLs in the 3D Printing directories download directly (preferred) and some display the ASCII file which has to be copied, pasted into an editor, and manually saved with a .STL extension.  I uploaded the same model generated in SolidWorks both as a binary STL and an ASCII STL, and the binary version downloads in the preferred method.
I propose that all future STLs be submitted in binary format and that the existing files get changed to binary when/if they are converted to MM units for ease of use.  Just my 2 cents.

**Comment by ISS-Mimic** [comment]
Agreed, let it be so!

**Comment by ISS-Mimic** [comment]
pretty sure this is done
