### ISSUE TITLE
Need to upload current HDMI breakout board holder STL

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#280]
The STL for this part is not current. The current design has a cut out in the bottom for the HDMI connector

![PXL_20211114_222130950.jpg](https://user-images.githubusercontent.com/24708086/141700895-c5714859-2e6b-4c53-969e-fb8e9879b713.jpg)

**Comment by streadgold** [comment]
This is the part:

https://github.com/ISS-Mimic/Mimic/blob/main/3D_Printing/Mimic_Structural_Compoments/HDMI%20Breakout%20Mount.stl

**Comment by cactus314** [comment]
> This is the part:
> 
> https://github.com/ISS-Mimic/Mimic/blob/main/3D_Printing/Mimic_Structural_Compoments/HDMI%20Breakout%20Mount.stl

That part works with the latest design of the HDMI breakout board and is what I am using on my current build.  I'm not sure it works with the earlier boards.  Also, it could use some improvement, but it works (mostly).

**Comment by Digisembler** [comment]
Corrected one uploaded, old one deleted.
