### ISSUE TITLE
Pi freeze and boot-resistant after frantic pos cmds

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#281]
Pi froze and wouldn't boot for many minutes. This was after a student frantically incremented the position command (add deets).

I wonder if the Pi polyfuse is getting tripped. Trying to think if this could be due to voltage spike coming thru USB from the potential induction/capacitance issue from the HDMI shield.

**Comment by SpaceTowel** [comment]
Closed as not fixed.  Keep minimal on student frantically increment position commands
