### ISSUE TITLE
Need to update comments at top of Stbd BGA code

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#282]
https://github.com/ISS-Mimic/Mimic/blob/ec43c3cdd9cd4f96fb357ab6fc39c6c150c0a42b/Arduino/Ard_StbdBGAs_r18/Ard_StbdBGAs_r18.ino#L8

The motor/BGA designations in the comments at the top of the Stbd BGA code don't appear to have been updated with the switch in BGA numbering (port should be fine?)

**Comment by juggler2000** [comment]
Cleaned up comments for Stbd and Port BGA code.
