### ISSUE TITLE
Print SAW

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#306]
Sam will update model - SAW mast

**Comment by ISS-Mimic** [comment]
Model is updated, just need someone to click print....

https://github.com/ISS-Mimic/Mimic/blob/main/3D_Printing/Solar_Array_Wing/HiFi_Solar_Array_Wing.stl

**Comment by cactus314** [comment]
I'll give one a go.  0.4mm nozzle though, so might be rougher than the re:3D ones (plus no dissolvable supports...)

**Comment by ISS-Mimic** [comment]
The one I printed (albeit only half of one due to size constraints) worked just fine without dissolvable supports, with "only touching buildplate" and the mast bridging distance isn't too bad

**Comment by juggler2000** [comment]
Thanks, Patrick!
