### ISSUE TITLE
New simulate graphic and funcationality

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#336]

**Comment by GodspeedDiscvry** [comment]
What am I supposed to do?

**Comment by streadgold** [comment]
We'll need new simulate orbit graphics and background etc, still need to define what all will be on the new screen so nothing for you at the moment until I figure out all the new stuff

**Comment by GodspeedDiscvry** [comment]
Loaded example screen, actual screen without buttons, and all depressed and regular buttons for the screen.  Also converted START STOP to play and stop icons.
