### ISSUE TITLE
Add deburring tool to BOM 

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#346]

**Comment by Digisembler** [comment]
Here's one.  Any will do, this one's pretty inexpensive with extra blades.
[https://www.amazon.com/zhuohai-Deburring-AntiSlip-Plastic-Aluminum/dp/B097K58SMZ/ref=sr_1_19?keywords=deburring+tool+for+plastic&qid=1677119192&sprefix=debur%2Caps%2C121&sr=8-19](url)
$8.95 at the time i looked it up.  Still needs to be added to BOM page, updates to totals, etc.
