### ISSUE TITLE
SAW mast coupler holes should use support 

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#349]
Mast holes for motor coupler are  not round and we want them to be round. Print with support.

**Comment by Digisembler** [comment]
This could be added to the print sheet to use support.  Could this also be cleaned up with a drill bit?  Cleaning holes with drill bits after printing can help solidify the material there, as well as provide a smoother surface for better wear.

**Comment by juggler2000** [comment]
I believe this is now rectified.
