### ISSUE TITLE
Passing data (joint angles, etc) from RasPi to Ard

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#35]
I was thinking one way to pass data for joint angles, etc, is via the .json standard, which uses named pairs: name, then value.  We could perhaps use an existing json library, like this: https://arduinojson.org/

**Comment by SupaTreadz** [comment]
Can do! Python makes JSON wrapping super easy

**Comment by juggler2000** [comment]
Leaning towards this Ard Json library, as it appears most widely used.  Currently have not clue how to use it.
https://arduinojson.org/

**Comment by juggler2000** [comment]
Does the Pi send data over serial by default, or do I need to hit "transmit".  GUI seems to lock up every time I hit transmit (the GUI is unresponsive, requiring hard reboot).

**Comment by streadgold** [comment]
If the Pi is locking up that means the Arduino isn't connected or it isn't detecting the Arduino. When booting the Pi, along with the kivy loading stuff it should list the connected serial port if there is one. Also in the error log file (in logs folder) it says if a successful connection occurred, if there are three serial connection errors listed it didn't connect to anything. 

This is connecting one of the Pi USB ports to the Arduino USB port right? Try another USB port on the Pi?

**Comment by streadgold** [comment]
Also I've only managed to get it working with USB to USB, so debugging might be tricky. Still working on USB to TX/RX pins

**Comment by juggler2000** [comment]
I forgot it would lock up w/o connection.  Iwas being cruel, and just had
serial pins going from Pi usb to O-scope.  Now trying the TX/RX pins (via
logic level shifting).  We'll see.

**Comment by streadgold** [comment]
Just FYI - I just tested my Mega connected to the Pi over USB and outputting serial to the computer over the TX1/RX1 pins. The code is in the Arduino folder. Not sure what needs to change for that to work on the your board but the concept works fine.

**Comment by ISS-Mimic** [comment]
Closing, I believe our tests confirm we have this problem down
