### ISSUE TITLE
Convert buttons to graphics

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#36]
Most GUI buttons are still the basic kivy widgets, need to replace them with custom graphics that have depth and can be depressed (replaced with depressed button graphic on_press)

**Comment by GodspeedDiscvry** [comment]
I believe I have provided all of these graphics.

**Comment by ISS-Mimic** [comment]
For default state yes, but this is for both unpressed and pressed buttons, so every button will need two graphics (for fanciness). Long term goal

**Comment by GodspeedDiscvry** [comment]
Oh, my.... yep.

**Comment by GodspeedDiscvry** [comment]
So, for all intensive purposes this is done for all currently active buttons and will be rolled in as each new button gets added.  The one exception is the back button.  We have hat drawn as a depress button - but it always floats on the black screen.  Do we still want to depress it?  Currently it shows the blue square while pressing.

**Comment by GodspeedDiscvry** [comment]
Done years ago... and then some!
