### ISSUE TITLE
IROSA - path for zip tie too tight. 

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#366]
Cannot fit zip tie thru slot. Widen slot or specify any print Paramus that would solve it.

**Comment by Digisembler** [comment]
Widened the slot by 0.2mm and deepened it by 0.07mm. Sent to juggler2000 to test.

**Comment by Digisembler** [comment]
Never heard back on this one, but I now have an stl set with the widened slot ready for upload.
