### ISSUE TITLE
Pi setup issue?  Step 6 (Lightstreamer)

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#37]
This was a non-issue.  Somehow missed step 4...

**Comment by streadgold** [comment]
hmm yeah that is a blank cd just to make sure you're in the home directory, might be unnecessary.

Did step 4 complete successfully? Does "node -v" and "npm -v" return anything?

**Comment by juggler2000** [comment]
User error -- missed step 4 somehow.

**Comment by juggler2000** [comment]
Hmm... I'm getting lots of colorful text from step &.  Perhaps I hosed something by doing steps 5 & 6 before 4.

![image](https://user-images.githubusercontent.com/24573838/35422851-46b6db80-0210-11e8-85f6-1b426bdab5d4.png)

**Comment by streadgold** [comment]
Does it just keep looping that over and over? Try the other command in step 7 if so

**Comment by juggler2000** [comment]
Seems to be having a downoad error... or something.

![image](https://user-images.githubusercontent.com/24573838/35423152-079ced20-0212-11e8-8eef-b1a6a2ee1a92.png)

**Comment by streadgold** [comment]
yeah that's the same problem susan was having. thought we solved it with that current setup list

**Comment by juggler2000** [comment]
seems like it might be an amazon server issue.  I rebooted the pi and tried again, but same result.

**Comment by juggler2000** [comment]
For step 12), if we are going to subject ppl to vi, we should prob provide the append and save&quit commands.

**Comment by juggler2000** [comment]
kept trying the same things, and eventually worked!  GUI up and running! Live data!

**Comment by streadgold** [comment]
nice! anything specific? perhaps you should save your command history so we can improve the setup steps if (when) others encounter that issue
