### ISSUE TITLE
QR code scan to show ISS module information

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#379]
- No app to install
- point to scan to show info real time. 
- Craig mentioned maybe host info locally?

**Comment by Surendra123A** [comment]
here is the QR that you asked for

**Comment by Surendra123A** [comment]
![ISS_module_information](https://github.com/ISS-Mimic/Mimic/assets/69196543/f9357a02-afe6-44ed-acf3-2306fe9a6159)
![ISS_module_information](https://github.com/ISS-Mimic/Mimic/assets/69196543/877125f0-d333-4ba1-96e4-c9977cfcf8e7)

**Comment by Surendra123A** [comment]
the top file is a .png
and the bottom one is a .svg

**Comment by Surendra123A** [comment]
I have used one of my repository to generate this QR code
[https://github.com/Surendra123A/project-QRcode](url)
any QR requirements 
Please do check out this repository
Thank You

**Comment by ISS-Mimic** [comment]
Thanks!
