### ISSUE TITLE
geopy probs

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#38]
Maybe I picked a bad time to git pull.

![image](https://user-images.githubusercontent.com/24573838/35783067-59836dd2-09c7-11e8-8ed1-bb6732d78e35.png)

**Comment by streadgold** [comment]
oops forgot to add to the install instructions, this should resolve:

sudo pip install geopy

**Comment by juggler2000** [comment]
Cool.  I was gunna  try something based on googles, but was worried that it
mattered where I installed from.  Does it?

**Comment by streadgold** [comment]
Actually dont do that just re-pull the code. I'm switching from geopy cause it causes lag

**Comment by juggler2000** [comment]
back in bidness! Thx!

**Comment by juggler2000** [comment]
Hmmm....

Wouldn't let me pull, wanted me to stash my telem...db (old issue, right?).  So, I deleted that and pulled fine.

Running python GUI.Py then threw a traceback error:
--------
File "GUI.py", line 8 in <module>
      import reverse_geocode
ImportError: No module named reverse geocode.

**Comment by ISS-Mimic** [comment]
oops, forgot to mention.

sudo pip install reverse-geocode

**Comment by juggler2000** [comment]
Hmm... Some scipy complaints during the install. Will try more tomorrow.
