### ISSUE TITLE
Manual Control Screen needs scalable text

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#385]
Text on control screen is in buttons, which means it doesnt respond to the normal text scaling method. Need labels over the buttons or something

**Comment by GodspeedDiscvry** [comment]
That screen is straight text placed over your buttons.  Do you want real buttons with text on them graphically instead?

**Comment by ISS-Mimic** [comment]
dont remember what prompted this so closing for the moment, add more info
