### ISSUE TITLE
SGANT screen has black boxes over graphics

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#386]

**Comment by GodspeedDiscvry** [comment]
The boxes are your touch screen "button" areas

**Comment by ISS-Mimic** [comment]
SGANT screen doesn't have any buttons other than the return button. I think its scaling on the off-screen TDRS graphics

**Comment by ISS-Mimic** [comment]
watched a full orbit and didnt see the boxes so this might be fixed? 🤷
