### ISSUE TITLE
Finish Orbit Screen

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#39]
- [x] Add orbit ground track to map image
- [x] Add daily orbit count
- [x] Add total orbit count
- [x] Fix TLE fetching
- [x] Add countdown till next pass
- [x] Add detection of visible passes
- [x] add visible pass data
- [x] add night region
- [x] Add orbital elements
- [x] Add ISS tle
- [x] Add GMT time
- [x] Add pass calculations (require location input)
- [x] Add 3d

**Comment by streadgold** [comment]
have to adjust orbit count from TLE + orbits since TLE was generated

**Comment by ISS-Mimic** [comment]
YES! GROUND TRACK ACHIEVED!!!! Not really that hard but took me a crazy long time to figure out

**Comment by ISS-Mimic** [comment]
functionally done, needs a few graphical updates that are in work
