### ISSUE TITLE
GUI screen not loading.  even after using just 'python GuI.py'

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#397]

**Comment by GodspeedDiscvry** [comment]
Working fine for me.  Try timez.  Sometimes it will lock up if timez not done.

**Comment by GodspeedDiscvry** [comment]
By the way, there are aliases for mpost things now.  "timez" for the sudo rdate thing, "mim" to change folders, "gui" once there to start gui.

**Comment by GodspeedDiscvry** [comment]
Okay - sorry.  We have to add alias bash file to each mimic.  I opened a sep issue to possibly do this.  As for the main branch not working.... may need Sam on that one.  I will go look and see if I accidentally added one of the new screens to the main branch which could break it.

**Comment by GodspeedDiscvry** [comment]
I did not see any new updates to anything on Main.  Chen says the one cloned Friday is fine, new one just shows white screen.

**Comment by ISS-Mimic** [comment]
I bet its another consequence of the username not being "pi". Maybe looking for the screens in the wrong spot or something. Will need to find and protect against that too

**Comment by ISS-Mimic** [comment]
Yep all the screens backgrounds are hard coded directories. will need some time to fix

**Comment by ISS-Mimic** [comment]
Okay I think I fixed it all on the susan branch. @SpaceTowel if you could checkout the susan branch, and pull, and see if that works that would be good.

`git checkout susan`
`git pull`

**Comment by ISS-Mimic** [comment]
also the telemetry has been offline since Thursday :(

**Comment by ISS-Mimic** [comment]
Will need to merge susan branch for fixes, but probably ready to do that anyway
