### ISSUE TITLE
Add Instruction to add Alias Bash file to Pi builds - Sam concur this is okay before I do it.  

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#398]
I have not looked at the wiki instruction regarding this, but maybe we should mention always doing a timez (sudo rdate) on each power up.  I think it would be good to add instruction on how to make aliases - especially the ones we use most.

**Comment by ISS-Mimic** [comment]
Sure we can include instructions for adding aliases. Eventually the code should maybe update the time itself but thats tricky

**Comment by ISS-Mimic** [comment]
I think new pi software handles the time pretty well, dont think this is needed anymore
