### ISSUE TITLE
Orbit globe image intermittently blank

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#443]
Occasionally the orbit globe image goes blank, presumably it's trying to reload the image while the file is being written by orbit globe? 

Decreasing the reload frequency may help

**Comment by juggler2000** [comment]
@GodspeedDiscvry thinks this is all set, but asked for @streadgold to confirm before closing.

**Comment by ISS-Mimic** [comment]
duplicate of #498 which will be fixed in VV branch merge
