### ISSUE TITLE
Update P1 + S1 models to increase the size of hole to accommodate motor and wire to fit through.  (likely by 0.5 to 1 mm) 

### ISSUE THREAD

**Issue by SpaceTowel** [ISS-Mimic/Mimic#455]

**Comment by juggler2000** [comment]
@Digisembler said he sent test files to @SpaceTowel to test print prior to closing this issue.

**Comment by streadgold** [comment]
![image](https://github.com/ISS-Mimic/Mimic/assets/24708086/2ad95749-c904-44e8-b8dc-273ef9b2c69f)

**Comment by ISS-Mimic** [comment]
based on the timestamps i dont think this has been completed but not sure
