### ISSUE TITLE
Somebody who understands github better please fix Wiki ToC to map to Have You Seen US Page

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#457]
The Wiki page for "Have you Seen Us - Historical Timeline" does not work when using the ToC on the right hand side.  If you click "Pages" above that and scroll down to it, it goes to the page.  I cannot figure out how to map to it.

**Comment by juggler2000** [comment]
Copy/pasted from URL into the GitHub wiki editor:
https://github.com/ISS-Mimic/Mimic/wiki/**Have-You-Seen-Us-%E2%80%90-Chronological-Timeline-of-ISS-Mimic**

* [Have You Seen Us... Chronological Timeline of ISS MIMIC](**./Have-You-Seen-Us-%E2%80%90-Chronological-Timeline-of-ISS-Mimic**)
