### ISSUE TITLE
Make code occasionally check for serial connections

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#47]
Code should continuously poll for serial devices attached - so it can handle attaching the devices after program begins. Also need to catch any errors if an attached serial device is detached while the program is running

**Comment by streadgold** [comment]
Might actually have this working. Checks all serial ports every 10 seconds and immediately at startup. Also unplugging the connection (even in the process of writing serial data!) seems to not crash the program. So far seems to be a very good improvement
