### ISSUE TITLE
Incorrect Days In Space listed on crew page

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#48]
Astronauts' days in space numbers do not agree with howmanypeopleareinspacerightnow.com.  And yes, it actually loaded for me!!!

**Comment by streadgold** [comment]
Crew page has the correct number, our screen shows the total number of days in space for the crewmember's lifetime, the howmanypeopleareinspacerightnow.com site I believe only shows the number of days for the current mission (which is odd because they are our data source for that info)
