### ISSUE TITLE
Program freezes occasionally 

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#498]
![PXL_20231214_235109784.jpg](https://github.com/ISS-Mimic/Mimic/assets/23327384/7ade80a5-33a8-4102-9960-c1d6d4a15f84)

Something to do with the orbit map perhaps

**Comment by ISS-Mimic** [comment]
Thats a different problem I think, every other lock up has shown the error loading image message

**Comment by juggler2000** [comment]
Reference point: since loading devsam on 1/29 it has not locked up (3 days ago).  But at that time wifi was switched to hotspot for the update, and has not been connected to any wifi since 1/29.  Might be unrelated.  Will continue to monitor.

**Comment by ISS-Mimic** [comment]
Image error is solved in VV branch - merging soon
