### ISSUE TITLE
Predict upcoming LOS

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#5]
Using SGANT elevation telemetry and/or GPS coords of ISS, add message to GUI user predicting an upcoming Loss of Signal. Would be a cool/possibly easy enhancement

**Comment by ISS-Mimic** [comment]
Kind of works 50% of the time. Some LOS cases occur without converging SASA+SGANT elevation angles. Log longitude and other potentially useful values and look for correlation.

**Comment by Digisembler** [comment]
This is a future enhancement, not to focus on now. Very difficult to accurately predict LOS since it depends on which handover mode they are using. - Sam
