### ISSUE TITLE
Update Mimic Frame CAD Model

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#512]
Hey @Digisembler, can you update the aluminum frame model? The one we have in the integrated mimic model is definitely outdated 

![image](https://github.com/ISS-Mimic/Mimic/assets/24708086/ebc0135f-6a5f-4ab9-9e8b-918957b34aa1)

![image](https://github.com/ISS-Mimic/Mimic/assets/24708086/f6241e16-32ac-4cda-bdf9-57bcf7c22ed8)

The 6x side legs are definitely the wrong length, and the L-brackets are the small version when at least some of them should be the large version.

This is crucial since its the only reference for folks building their own

**Comment by streadgold** [comment]
https://github.com/ISS-Mimic/Mimic/blob/main/Wiki/Mimic%20One%20Frame%20Updated.pptx

**Comment by Digisembler** [comment]
Model can get updated - the powerpoint of the frame build is in the wiki under Mimic One Frame Updated.pptx

**Comment by Digisembler** [comment]
So there are some issues with the tool i'm using for this - i cannot add the T plates and as far as i can tell, there's only the small 90 degree brackets.  We'll just have to point out which are which, or cad up those brackets from outside the tool.  Updated dimensions as best possible to the link above, realizing that everyone's specific build may have to adjust slightly for their build.  Step file included here to check out and receive comments back.
[UpdatedFrame240203.zip](https://github.com/ISS-Mimic/Mimic/files/14154288/UpdatedFrame240203.zip)
