### ISSUE TITLE
Innovation Week Goals

### ISSUE THREAD

**Issue by GodspeedDiscvry** [ISS-Mimic/Mimic#52]
**Double the Size**

- [x] Get metal for test stand to support full station
This is done for now - but still acquiring better metal and longer metal for more stability.  We can even live with the diagonal sick going up into N2N since we don't have an HTV print yet. 

- [x] Integrate pressurized section in full size test bed to illustrate size and magnify interest.  
For the most part this is done.  We are adding more pressurized elements.  I will need to eventually move the module stack on its base (and redrill holes for RS) to accommodate the longer Lab module - but think the diaganol support will work for I-week.

- [x] Determine post material (metal/acrylic, etc.) to support pressurized elements and route wires, possibly with LEDs inside and/or flags/etc. outside.

- [x] Determine where to cut cross pieces of 80/20 (currently 30+ inch, prob drop to 28ish)
I propose we do not do this at this time.  I may need one of the longer feet  to use for module stack support

- [x] Print or procure end caps for extruded aluminum (because it's sharp).  https://www.thingiverse.com/thing:1876628

- [x] Print support caps for risers and spindle

**3D prints still needed for module stack in order of priority (to support above "Double the Size" goal)**

- [ ]new caps for Lab with magnet insets
- [ ] S0/Lab connector piece
- [ ] PMM
- [ ] Cupola (if we had CAD model done)
- [ ] JEM
- [ ] JLP

**High Def Models**

- [ ] See truss structure when not MLI

- [x] Resolve Blender model issues 

- [ ] Handrails & details?

**Mechtronics**

- [ ] Functional TRRJ

- [ ] ARD cmd = 10 DC motors + 2 servos + LEDs

 **Pressurized**

- [ ] Focus some LEDs into a functionality

**GUIS**

- [x] Un-eWeek backgrounds

- [ ] ideas for subsystem page content

- [ ] Al pages present with some level of content and standard GUI MIMIC template

**Stretch**

- [ ] AR/Unity - where is the sun?
- [ ] Print all in SLA

**Comment by ISS-Mimic** [comment]
Actually accomplished most of this and I-week is over, closing. We can maintain new issues with the new truss backbone on Issue #77
