### ISSUE TITLE
Math domain error

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#523]
![image](https://github.com/ISS-Mimic/Mimic/assets/24708086/14c39eb3-25ea-46d3-8fe9-dab4fb7b9a32)

occurred after running code for ~5 days, add error checking

**Comment by ISS-Mimic** [comment]
solved in VV branch - merging soon

**Comment by ISS-Mimic** [comment]
should be solved in VV branch - mu is a constant so must be sma issue? adding check
