### ISSUE TITLE
Mini - Russian segment modules missing one STL in print list

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#540]
screenshot of build plate shows both halves, but print list only shows one. 

https://github.com/ISS-Mimic/Mimic/tree/main/EXTRAs/Mini/3D_Printing/Russian_Segment

![image](https://github.com/ISS-Mimic/Mimic/assets/24573838/8d900808-43b1-4ab6-a439-1bc70322fc96)

**Comment by SpaceTowel** [comment]
README file updated
