### ISSUE TITLE
2B, 4B BGA sign issue

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#57]
2B and 4B signs appear flipped when mimic'ing ISS stream.  

This was initially confounding, because without the streaming data, they all seem to properly move to the startup position (30 deg).  But this is because the initialization values had signs flipped for these (and forgotten).
![image](https://user-images.githubusercontent.com/24573838/45133410-acdae600-b15a-11e8-9c9c-64a0ae0dbb9a.png)

Likely need motor/encoder polarities swapped at the motor shield (or signs swapped in code).

**Comment by ISS-Mimic** [comment]
@juggler2000 is this one solved? Or was this still the encoder problem?

**Comment by juggler2000** [comment]
Solved, meaning I didn't change anything and it has been working fine.  There may be a phantom encoder problem that periodically manifests, so I'll take out insanity insurance.
