### ISSUE TITLE
Bill of Materials not formatted correctly

### ISSUE THREAD

**Issue by TheRealFakeAdmin** [ISS-Mimic/Mimic#603]
## Description
The [Bill of Materials](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials) wiki page formatting is missing the bullet points/new-lines under the sections [Required Tools](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials#required-tools) & [Useful Tools](https://github.com/ISS-Mimic/Mimic/wiki/Build-Instruction%3A-Bill-of-Materials#useful-tools).

## Current
```
### Required Tools
3D Printer
Small Phillips Head Screw Driver
Soldering Iron (if assembling boards)

### Useful Tools
Deburring Tool for cleaning up 3d prints
Drill bits for opening up plastic holes
Multimeter for debugging
Paint Pens / Airbrush for aesthetics
Caffeine
```

## Expected
```
### Required Tools
- 3D Printer
- Small Phillips Head Screw Driver
- Soldering Iron (if assembling boards)

### Useful Tools
- Deburring Tool for cleaning up 3d prints
- Drill bits for opening up plastic holes
- Multimeter for debugging
- Paint Pens / Airbrush for aesthetics
- Caffeine
```

**Comment by ISS-Mimic** [comment]
Done thanks for the copy pastability ;)
