### ISSUE TITLE
Extrusion Components

### ISSUE THREAD

**Issue by Digisembler** [ISS-Mimic/Mimic#63]
- [x] Model 8020 nut for attaching to extrusions.
1/8 inch hole for rods
need design, stls and makerbot pla sliced files
- [x] Model 8020 cone for attaching to extrusions.
1/8 inch hole for rods
need design, stls and makerbot pla sliced files

**Comment by Digisembler** [comment]
- [ ] Print SAW end caps (2)

- [ ] Print SAW canisters (2)

- [ ] Print Node 2 body

- [ ] Print Node 2 cap

- [ ] Print JEM PM

- [ ] Print JEM EF

- [ ] Print JEM ES

- [ ] Print replacement COF body

**Comment by Digisembler** [comment]
- [ ] Explore ELC models from Blender model.

- [ ] Modify ELC1 models to have small magnet at CAS interface, FRAM/direct mount sites/ExPCA/Grapples
- [ ] Modify ELC2 models to have small magnet at CAS interface, FRAM/direct mount sites/ExPCA/Grapples
- [ ] Modify ELC3 models to have small magnet at CAS interface, FRAM/direct mount sites/ExPCA/Grapples
- [ ] Modify ELC4 models to have small magnet at CAS interface, FRAM/direct mount sites/ExPCA/Grapples
- [ ] Modify AMS model to have small magnet at CAS interface, Grapples

**Comment by juggler2000** [comment]
This list is fantastic.  Which are print-ready?

**Comment by Digisembler** [comment]
working... btw, i completed a Lab mod (and printed it) that has two beautiful endcones and a cylinder (PLA is my BFF!)
Also, need some help (thoughts/technical?) on how to setup/upload stls here...

**Comment by streadgold** [comment]
If you go to the Code section, I just added a "Printing" folder, if you click on that then "Upload Files" at the top you can upload them there. Not sure what our file size limit is for our whole repository but STLs usually aren't that big right?

**Comment by Digisembler** [comment]
Great thx.  Any way to edit the text with the commit after committing? i forgot to add the ELM PS print notes... (i.e. I'd add" Print the non-cbm end down, no supports. Again, PLA recommended.  Also setup for a magnet for the PIU interface on the top, same size as PM").

**Comment by streadgold** [comment]
Not sure if you can edit a commit message

**Comment by streadgold** [comment]
Oh so you can add comments to each commit, might be easier than editing it. 

Also Craig, your commit messages put mine to shame haha. Mine are all "added stuff, changed things"

**Comment by Digisembler** [comment]
Ok, 2019!  I have the S6 (P6) array mount printed.
I fixed the S1 model (rotated the motor mount hole) and am printing now (~ 4 hrs)
We should clean up the above list of things to print, i think it's outdated and start a new one soon.

**Comment by ISS-Mimic** [comment]
Yep, concur. Closing this issue, add any new components and tasks to Issue #77
