### ISSUE TITLE
Pytz module missing

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#64]
Pytz Python module missing.  Okay to install v3. 2 as listed here?  

https://www.raspberrypi.org/forums/viewtopic.php?t=86500

Showed up as burp when trying to run mimic. Tripped on line 7 of GUI. py (import pytz).

**Comment by ISS-Mimic** [comment]
Probably shouldn't use that version as we aren't currently on Python3 (maybe we should change that?).
Try:
sudo pip install pytz

**Comment by juggler2000** [comment]
Worked! Thx!
