### ISSUE TITLE
Prettify Mimic Wiring

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#74]
Re-wire some (most?) mimic wire bundles to use RJ45 cables and tidy ethernet connections

**Comment by Digisembler** [comment]
Whew - won't this increase the diameter of the bundles? Will have to open hole diameters for wiring/casings.

**Comment by streadgold** [comment]
If we did that for the entire cable run yes, but this is envisioned more for once the cables leave the model - so not required for cables coming down the support posts on the module stack for instance. Really just needed for the BGAs to get them into shielded cables. So for inboard wiring we'll probably stick with bare wires until they come out in the base or whatever.
