### ISSUE TITLE
Transition model to new black aluminum structure

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#77]
Highest priority is getting the port outboard truss up and running again.

- [x] Requires new mounting interface for S3/P3

- [x] Need threaded rod and nuts to tighten truss

- [x] Wiring #80 needs to be accomplished

- [x] Print new truss endcaps

feel free to edit and add more...

@Digisembler @GodspeedDiscvry @juggler2000

**Comment by Digisembler** [comment]
Modified the truss endcaps to match the new heights.  Printed those in black PLA.
Reprinting the S1/P1 Mounts in black PLA (fixes/completes S3/P3 new mounting above).
#3 x 36" threadrod and nuts ordered to tighten inboard truss.  (really wondering why we didn't just use a flat bar and set screws in each module... would have been easier/tighter... just thought of it, so, that's probably why, but doesn't really keep the stack axially tightened.)

**Comment by ISS-Mimic** [comment]
Bueno! If it was difficult to find the rod/nuts it might be worthwhile to link the part numbers / links to the products somewhere here for future reference

**Comment by Digisembler** [comment]
Nuts:
https://www.grainger.com/product/2GA49?cm_mmc=EMT-_-10376092-_-ShippingConf2018NavBar-_-OnlineGuest-KPIRPE-_-Item&RIID=50635142275&GID=&mid=EMT-_-10376092-_-ShipConfirmation-_-Item&rfe=6b8e4fd0d0254c6f348a2870942a7662d7f525f21e1fba5d2722ed2880f81439&gcrfe=6b8e4fd0d0254c6f348a2870942a7662d7f525f21e1fba5d2722ed2880f81439

Threadrod:
https://www.grainger.com/product/21YN98?cm_mmc=EMT-_-10339122-_-OrderConf2018NavBar-_-OnlineGuest-KPIRPE-_-Item&RIID=50635142275&GID=&mid=EMT-_-10339122-_-OrderConfirmation-_-Item&rfe=6b8e4fd0d0254c6f348a2870942a7662d7f525f21e1fba5d2722ed2880f81439&gcrfe=6b8e4fd0d0254c6f348a2870942a7662d7f525f21e1fba5d2722ed2880f81439

We'll see if these work when they get in.

**Comment by Digisembler** [comment]
Threadrods delivered, cut, installed with nuts.  New zip-tie outboard support blocks designed/printed (need small zip ties for today... no wider than 1/8", probably 3-5" long, minimum of 4 needed)

**Comment by ISS-Mimic** [comment]
Completed - or at least back to where we were on the old frame. Will bring zip ties tomorrow
