### ISSUE TITLE
FYI: Motor info for connection to custom PCB

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#8]
This is the motor we are using right now (for BGA's and SARJ's): https://www.servocity.com/175-rpm-micro-gearmotor-w-encoder

And this is the mating connector: https://www.servocity.com/zh-series-jst-6-pin-connector-1-5mm-pitch

**Comment by juggler2000** [comment]
Should we close this?  Seems like it needs to live somewhere, but it isn't an "issue".  I'm sure there's a place for such things, but it doesn't seem like it should be the wiki.

**Comment by streadgold** [comment]
This seems like a good candidate to be a note "card" in one of the projects - I'll copy over
