### ISSUE TITLE
Truss Cable Choice

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#80]
Related to Issue #74 

We talked about using cat-7 cables for the runs down from the truss back to the arduino but maybe we should actually use USB-C?

Pros:
USB-C are 12-pin cables, perfect for our 12-pin slip rings. So 4 cables total coming from truss, instead of 8. 
USB-C are slimmer and look more high-tech?

Cons:
Breakout board would have slip ring wires soldered directly on, wouldn't look as clean.
Breakout board is a little wide and wouldn't hide as well as ethernet doubler 

Thoughts?
@Digisembler @GodspeedDiscvry @juggler2000

**Comment by streadgold** [comment]
USB-C won't work :( 

They require magic electrical nonsense to work. Back to ethernet

**Comment by ISS-Mimic** [comment]
Ethernet it is.
