### ISSUE TITLE
Switch labels of BGAs in code and on model

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#86]
Somewhere along the way we switched witch motors plug in to which IEA PCBs. We need to reverse the labels in the code and on the Cat7 cables. 

2A <-> 4A
2B <-> 4B

**Comment by juggler2000** [comment]
r9 code has them swapped.  Let's confirm it works, then hopefully close this one.

**Comment by juggler2000** [comment]
Done. Works. Goodness.
