### ISSUE TITLE
SARJ motor problems

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#89]
PSARJ motor is not really doing what is commanded all of the time - might be connection problem?

**Comment by juggler2000** [comment]
Seems related to the limited and shared interrupts issue. Temporary solution is to try the third Ard Metro board with third motor shield to drive both SARJs, and might as well drive TRRJ servos from that one, too. I'll try to have code ready for tomorrow.

**Comment by juggler2000** [comment]
Just uploaded new code for a third Ard to control the SARJs.  This will use the happy/friendly/reliable pins that have worked well for BGAs.  #AdmittingDefeat

**Comment by juggler2000** [comment]
PSARJ Presently Performing Properly, Per Prior Posts Procedure.
