### ISSUE TITLE
BGA 2A spins wrong way

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#94]
2A BGA rotates the wrong direction

**Comment by ISS-Mimic** [comment]
Might be a re-occurrence of a previous software issue where the encoders randomly swap. Could also have been a wiring mistake. Wiring has been swapped and all arrays are working properly now - so if a problem happens now that should indicate a software error rather than a wiring problem

**Comment by ISS-Mimic** [comment]
Haven't noticed this issue in a long time, and the arrays have been run for hours consecutively. Closing for now.
