### ISSUE TITLE
S1/P1 mounting improvements 

### ISSUE THREAD

**Issue by streadgold** [ISS-Mimic/Mimic#95]
We need to further constrain the truss movement at the S1/P1 attachment sites

**Comment by Digisembler** [comment]
will consider the m3 threadrod method through the module, into the 20x20 mount cap.

**Comment by Digisembler** [comment]
m3 threadrod is the current solution, btw. Models are setup to hold from the 3-1-0-1-3 trusses with two threadrods. Double nuts on each end lock it, or use threadlocker or a bit of glue to hold them.
