### ISSUE TITLE
Support mounting hole locations

### ISSUE THREAD

**Issue by ISS-Mimic** [ISS-Mimic/Mimic#96]
Need to determine final locations for the mounting holes in the module stack - accounting for visiting vehicles and internal circuit boards

**Comment by Digisembler** [comment]
Will add to lab and service module. 0.2in diam holes, 0.28" deep.

**Comment by Digisembler** [comment]
Ended up putting holes in Node 2 and Node 1 and up the Service Module (Zvezda) nadir port stack.

**Comment by Digisembler** [comment]
Seems to be finished
